### ISSUE TITLE
Currency symbols not updating in price chart

### ISSUE THREAD

**Issue by SvetStanev** [samc05991/crypto-ath-support#2]
When I open the price chart and switch between FIAT currencies the currency symbol on the chart doesn't get updated.

![Capture](https://user-images.githubusercontent.com/38881530/103008718-78f37c80-452d-11eb-976d-b87e3b196c62.PNG)

As can be seen from the image above, I've selected GBP as fiat currency but the price chart still uses the dollar symbol.

Best wishes,
Svet

**Comment by samc05991** [comment]
Hey @iDuriel this issue has been resolved in the latest version
